In [2]:
import pandas as pd
!pip3 install openpyxl

DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621
Requirement already satisfied: openpyxl in /usr/local/lib/python3.9/site-packages (3.0.10)
Requirement already satisfied: et-xmlfile in /usr/local/lib/python3.9/site-packages (from openpyxl) (1.1.0)
DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621
WARNING: You are using pip version 22.0.4; however, version 22.2.2 is available.
You should consider upgrading via the '/usr/local/opt/python@3.9/bin/python3.9 -m pip install --upgrade pip' command.

In [4]:
from datasets import load_dataset
dataset = load_dataset("md_gender_bias")

/usr/local/lib/python3.9/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
No config specified, defaulting to: md_gender_bias/new_data
Reusing dataset md_gender_bias (/Users/toby.bell/.cache/huggingface/datasets/md_gender_bias/new_data/1.0.0/8ae77b51acf93383161cc954b146159291beca6c979b54ce228c46db86116c05)
100%|██████████| 1/1 [00:00<00:00, 49.64it/s]

In [5]:
dataset['text']

DatasetDict({
    train: Dataset({
        features: ['text', 'original', 'labels', 'class_type', 'turker_gender', 'episode_done', 'confidence'],
        num_rows: 2345
    })
})

In [3]:
df = pd.read_csv("ConvAbuseEMNLPfull.csv")
df

,example_no,annotator_id,conv_id,prev_agent,prev_user,agent,user,bot,is_abuse.1,is_abuse.0,...,type.intellectual,type.racist,type.sexist,type.sex_harassment,type.transphobic,target.generalised,target.individual,target.system,direction.explicit,direction.implicit
0,0,Annotator7,245846.0,Does that question interest you?,because my finger is happy,Why do you say your finger is happy?,do you rember japan,E.L.I.Z.A.,1,0,...,0,0,0,0,0,0,0,0,0,0
1,1,Annotator7,159183.0,Does it please you to believe I am a nobe jocky?,bye bye,Please go on.,do you like it hard,E.L.I.Z.A.,0,1,...,0,0,0,0,0,0,0,0,0,0
2,2,Annotator7,340147.0,Have you tried?,dick,Please go on.,oh what a pickle dear monastery,E.L.I.Z.A.,1,0,...,0,0,0,0,0,0,0,0,0,0
3,3,Annotator7,95cbaab0f8cb4cb59a3393e7fc61cafe,Will you be travelling in Economy Class?,yes,What city will you be flying from?,Sydney,CarbonBot,1,0,...,0,0,0,0,0,0,0,0,0,0
4,4,Annotator7,270732.0,Please go on.,Hello.,How do you do. Please state your problem.,how old are you?,E.L.I.Z.A.,1,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12763,12763,Annotator5,88637.0,Please go on.,who are you,Would you prefer if I were not []?,what,E.L.I.Z.A.,0,1,...,0,0,0,0,0,0,0,0,0,0
12764,12764,Annotator5,95cbaab0f8cb4cb59a3393e7fc61cafe,And what city will you be flying to?,To Bangalore,I'm not sure about your destination airport. A...,To Bangalore,CarbonBot,1,0,...,0,0,0,0,0,0,0,0,0,0
12765,12765,Annotator5,ac0d288727f943e396346de6b96e2e34,Will you be travelling in Economy Class?,yes,What city will you be flying from?,London,CarbonBot,1,0,...,0,0,0,0,0,0,0,0,0,0
12766,12766,Annotator7,fa612f49abb64c459b7ccdf08fda2e8f,What city will you be flying from?,from Berlin to New York,A one-way flight from Berlin-Schönefeld Airpor...,from New York to London,CarbonBot,1,0,...,0,0,0,0,0,0,0,0,0,0
12767,12767,Annotator4,fb6eefee0b9e4e1f8306a0debdaf9132,_,_,_,hello,CarbonBot,1,0,...,0,0,0,0,0,0,0,0,0,0

In [32]:
df2

,MS-A02: Age - five year age bands - all usual residents [note 1],Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21
0,Table population: All usual residents,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Geographic level: Local Government District,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Source: Census 2021,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Some cells refer to notes which can be found o...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,This worksheet contains two tables presented v...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,Table MS-A02a presents counts and Table MS-A02...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,MS-A02a: Age - five year age bands - all usual...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,Geography,Geography code,All usual residents,0-4 years,5-9 years,10-14 years,15-19 years,20-24 years,25-29 years,30-34 years,...,45-49 years,50-54 years,55-59 years,60-64 years,65-69 years,70-74 years,75-79 years,80-84 years,85-89 years,90+ years
8,Northern Ireland,N92000002,1903174,113820,124475,126918,113203,111386,116409,126050,...,121670,130967,129276,113049,93464,83467,66377,43776,25879,13512
9,Antrim and Newtownabbey,N09000001,145662,8320,9367,9788,8642,7901,8683,9582,...,9834,10294,10013,8448,7036,6421,5158,3447,2023,1015
10,"Armagh City, Banbridge and Craigavon",N09000002,218656,14175,15431,15814,13027,11570,13321,14723,...,14388,14952,14452,12222,9826,9027,7237,4798,2693,1409
11,Belfast,N09000003,345417,19788,21328,21213,21412,28919,26735,26685,...,19653,21282,21940,19499,14813,12139,9958,6932,4478,2526
12,Causeway Coast and Glens,N09000004,141745,7973,8878,9113,8326,7873,7713,8460,...,9322,10412,10150,9171,7769,6990,5659,3718,2126,1051
13,Derry City and Strabane,N09000005,150756,9291,10270,10417,9322,8750,8941,9833,...,9798,10730,10656,8845,7440,6515,4734,3100,1673,695
14,Fermanagh and Omagh,N09000006,116811,7331,7821,8084,7175,6048,6294,6796,...,7568,7897,7992,7272,6534,5647,4085,2734,1566,871
15,Lisburn and Castlereagh,N09000007,149106,9040,9612,9746,7909,7124,8958,10305,...,9647,10523,10526,8943,7146,6443,5413,3804,2291,1117
16,Mid and East Antrim,N09000008,138995,7535,8176,8483,7912,7235,7689,8488,...,9198,10674,10297,9008,7511,7024,5701,3753,2207,1144
17,Mid Ulster,N09000009,150293,10601,10973,11058,9479,8404,9206,10363,...,9934,9761,9049,7918,6619,5754,4499,2958,1767,928
18,"Newry, Mourne and Down",N09000010,182073,11722,12951,13151,11201,10022,10354,11334,...,11583,12609,12423,10758,9138,7782,5992,3880,2347,1189
19,Ards and North Down,N09000011,163660,8044,9668,10051,8798,7540,8515,9481,...,10745,11833,11778,10965,9632,9725,7941,4652,2708,1567
20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,MS-A02b: Age - five year age bands - all usual...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,Geography,Geography code,All usual residents,0-4 years,5-9 years,10-14 years,15-19 years,20-24 years,25-29 years,30-34 years,...,45-49 years,50-54 years,55-59 years,60-64 years,65-69 years,70-74 years,75-79 years,80-84 years,85-89 years,90+ years
23,Northern Ireland,N92000002,1903174,0.059805,0.065404,0.066688,0.059481,0.058526,0.061166,0.066231,...,0.06393,0.068815,0.067927,0.0594,0.04911,0.043857,0.034877,0.023002,0.013598,0.0071
24,Antrim and Newtownabbey,N09000001,145662,0.057119,0.064306,0.067197,0.059329,0.054242,0.059611,0.065782,...,0.067512,0.07067,0.068741,0.057997,0.048304,0.044082,0.035411,0.023664,0.013888,0.006968
25,"Armagh City, Banbridge and Craigavon",N09000002,218656,0.064828,0.070572,0.072324,0.059578,0.052914,0.060922,0.067334,...,0.065802,0.068381,0.066095,0.055896,0.044938,0.041284,0.033098,0.021943,0.012316,0.006444
26,Belfast,N09000003,345417,0.057287,0.061746,0.061413,0.061989,0.083722,0.077399,0.077254,...,0.056896,0.061612,0.063517,0.056451,0.042884,0.035143,0.028829,0.020068,0.012964,0.007313
27,Causeway Coast and Glens,N09000004,141745,0.056249,0.062634,0.064292,0.058739,0.055543,0.054415,0.059685,...,0.065766,0.073456,0.071607,0.064701,0.05481,0.049314,0.039924,0.02623,0.014999,0.007415
28,Derry City and Strabane,N09000005,150756,0.061629,0.068123,0.069098,0.061835,0.058041,0.059308,0.065225,...,0.064992,0.071175,0.070684,0.058671,0.049351,0.043216,0.031402,0.020563,0.011097,0.00461
29,Fermanagh and Omagh,N09000006,116811,0.06276,0.066954,0.069206,0.061424,0.051776,0.053882,0.058179,...,0.064788,0.067605,0.068418,0.062254,0.055937,0.048343,0.034971,0.023405,0.013406,0.007456
30,Lisburn and Castlereagh,N09000007,149106,0.060628,0.064464,0.065363,0.053043,0.047778,0.060078,0.069112,...,0.064699,0.070574,0.070594,0.059977,0.047926,0.043211,0.036303,0.025512,0.015365,0.007491
31,Mid and East Antrim,N09000008,138995,0.054211,0.058822,0.061031,0.056923,0.052052,0.055319,0.061067,...,0.066175,0.076794,0.074082,0.064808,0.054038,0.050534,0.041016,0.027001,0.015878,0.008231
32,Mid Ulster,N09000009,150293,0.070536,0.073011,0.073576,0.06307,0.055917,0.061254,0.068952,...,0.066098,0.064946,0.060209,0.052684,0.044041,0.038285,0.029935,0.019682,0.011757,0.006175
33,"Newry, Mourne and Down",N09000010,182073,0.064381,0.071131,0.072229,0.061519,0.055044,0.056867,0.06225,...,0.063617,0.069252,0.068231,0.059086,0.050189,0.042741,0.03291,0.02131,0.01289,0.00653
34,Ards and North Down,N09000011,163660,0.049151,0.059074,0.061414,0.053758,0.046071,0.052029,0.057931,...,0.065654,0.072302,0.071966,0.066999,0.058854,0.059422,0.048521,0.028425,0.016546,0.009575